import org.apache.tools.ant.filters.ReplaceTokens
import org.objectweb.asm.*

import java.nio.file.Files
import java.nio.file.LinkOption

plugins {
    id 'java'
}

ext {
    configureSigFixRemapper = {
        it.extraPreApplyVisitor({ c, v ->
            return new ClassVisitor(Opcodes.ASM9, v) { // this will remove the signatures where needed
                @Override
                void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
                    try {
                        super.visit(version, access, name, signature, superName, interfaces)
                    } catch (Throwable ignored) {
                        super.visit(version, access, name, null, superName, interfaces) // remove faulty signature
                    }
                }

                @Override
                RecordComponentVisitor visitRecordComponent(String name, String descriptor, String signature) {
                    try {
                        return super.visitRecordComponent(name, descriptor, signature)
                    } catch (Throwable ignored) {
                        return super.visitRecordComponent(name, descriptor, null) // remove faulty signature
                    }
                }

                @Override
                FieldVisitor visitField(int access, String name, String descriptor, String signature, Object value) {
                    try {
                        return super.visitField(access, name, descriptor, signature, value)
                    } catch (Throwable ignored) {
                        return super.visitField(access, name, descriptor, null, value) // remove faulty signature
                    }
                }

                @Override
                MethodVisitor visitMethod(int access, String name, String descriptor, String signature, String[] exceptions) {
                    MethodVisitor mv;
                    try {
                        mv = super.visitMethod(access, name, descriptor, signature, exceptions)
                    } catch (Throwable ignored) {
                        // remove faulty signature
                        mv = super.visitMethod(access, name, descriptor, null, exceptions)
                    }
                    return new MethodVisitor(Opcodes.ASM9, mv) {
                        @Override
                        void visitLocalVariable(String name1, String descriptor1, String signature1, Label start, Label end, int index) {
                            try {
                                super.visitLocalVariable(name1, descriptor1, signature1, start, end, index)
                            } catch (Throwable ignored) {
                                // remove faulty signature
                                super.visitLocalVariable(name1, descriptor1, null, start, end, index)
                            }
                        }
                    }
                }
            }
        })
    }
}

sourceSets.configureEach { ss ->
    def processSource = tasks.register("process${ss.name.capitalize()}Source", Sync) {
        from ss.java
        inputs.property 'mod_version', project.mod_version
        inputs.property 'mc_version', project.mc_version
        filter(ReplaceTokens, tokens: [
                MOD_VERSION: project.mod_version,
                MC_VERSION : project.mc_version
        ])
        into layout.buildDirectory.dir("src/${ss.name}")
    }

    tasks.named(ss.compileJavaTaskName) {
        source = processSource.get()
        dependsOn processSource
    }

    tasks.named(ss.processResourcesTaskName) {
        inputs.property("mod_version", mod_version)
        inputs.property("mc_version", mc_version)
        filesMatching("mcmod.info") {
            expand(inputs.properties)
        }
    }
}

// Create main symlink for easier symlink access
tasks.register('symlinkJars') {
    dependsOn 'build'

    doLast {
        File symlinkDir = layout.buildDirectory.dir("libs").get().asFile;
        File[] files = symlinkDir.listFiles({ f ->
            f.isFile() && !Files.isSymbolicLink(f.toPath()) && f.name.endsWith(".jar")
        } as FileFilter)

        for (File file : files) {
            java.nio.file.Path symlinkPath = symlinkDir.toPath().resolve(file.getName().replace("-${mod_version}", "")).toAbsolutePath()
            java.nio.file.Path targetPath = file.toPath().toAbsolutePath()

            if (Files.exists(symlinkPath, LinkOption.NOFOLLOW_LINKS)) {
                java.nio.file.Path currentLink = Files.readSymbolicLink(symlinkPath)
                if (currentLink == targetPath) continue

                Files.delete(symlinkPath)
            }

            try {
                Files.createSymbolicLink(symlinkPath, targetPath)
            } catch (IOException e) {
                throw new GradleException("Error creating generic symlink", e)
            }
        }
    }
}
build.finalizedBy symlinkJars

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:unchecked"
    options.deprecation = true
}
