import xyz.wagyourtail.unimined.mapping.formats.at.LegacyATReader

plugins {
    id 'java'
    alias(libs.plugins.unimined)
    id 'blockhelper.build-conventions'
}

group = project.mod_group
version = project.mod_version

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(6)
    }
}

repositories {
    flatDir {
        name = 'libs'
        dirs('libs')
    }
}

LegacyATReader.leinient = true // Forge's AT just ignores invalid entries

unimined.minecraft {
    version project.mc_version

    minecraftForge {
        loader project.forge_version
    }

    mappings {
        stubs(["official", "searge"]) {
            c("BaseMod", "net/minecraft/src/BaseMod")
            c("BaseModMp", "net/minecraft/src/BaseModMp")
            c("ModLoader", "net/minecraft/src/ModLoader")
            c("ModLoaderMp", "net/minecraft/src/ModLoaderMp")
            // c("mod_BlockHelper", "net/minecraft/src/mod_BlockHelper") //  Not in 1.5.x!
            // c("mod_BlockHelper\$Accessor", "net/minecraft/src/mod_BlockHelper\$Accessor") //  Not in 1.5.x!
            c("Packet230ModLoader", "net/minecraft/src/Packet230ModLoader")
        }
    }

    mods.modImplementation {
        remapper ext.configureSigFixRemapper
    }
}

remapJar {
    prodNamespace("searge")
}

dependencies {
    modImplementation(":CodeChickenCore 0.8.7.3-fix1")
    modImplementation(":NotEnoughItems 1.5.2.28")
}
