import xyz.wagyourtail.unimined.mapping.formats.at.LegacyATReader

plugins {
    alias(libs.plugins.unimined)
    id 'blockhelper.build-conventions'
}

group = project.mod_group
version = project.mod_version

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(6)
    }
}

repositories {
    flatDir {
        name = 'libs'
        dirs('libs')
    }
    unimined.fabricMaven
    unimined.legacyFabricMaven
    unimined.minecraftForgeMaven
    unimined.wagYourMaven('releases')
}

LegacyATReader.leinient = true // Forge's AT just ignores invalid entries

sourceSets {
    client {
    }
    server {
    }
    mcpcplus {
    }
}
tasks.named('jar') { // Disable jar for main sourceSet
    enabled = false
}

/* The hard way for MCPC+ */
tasks.register('mcpcplusJar', Jar) {
    from sourceSets.mcpcplus.output
    archiveClassifier.set('mcpcplus')
}
artifacts {
    archives mcpcplusJar
}

unimined.minecraft(sourceSets.client) {
    version project.mc_version
    side "client"

    minecraftForge {
        loader project.forge_version
    }

    mappings {
        retroMCP(project.mc_version_mcp)
        stubs(["official", "retroMCP"]) {
            c("BaseMod", "net/minecraft/src/BaseMod")
            c("BaseModMp", "net/minecraft/src/BaseModMp")
            c("ModLoader", "net/minecraft/src/ModLoader")
            c("ModLoaderMp", "net/minecraft/src/ModLoaderMp")
            c("mod_BlockHelper", "net/minecraft/src/mod_BlockHelper")
            c("mod_BlockHelper\$Accessor", "net/minecraft/src/mod_BlockHelper\$Accessor")
            c("Packet200ModLoader", "net/minecraft/src/Packet200ModLoader")
            c("Packet230ModLoader", "net/minecraft/src/Packet230ModLoader")
        }
    }

    mods.modImplementation {
        remapper ext.configureSigFixRemapper
    }
}

unimined.minecraft(sourceSets.server) {
    version project.mc_version
    side "server"

    minecraftForge {
        loader project.forge_version
    }

    mappings {
        retroMCP(project.mc_version_mcp)
        stubs(["official", "retroMCP"]) {
            c("BaseMod", "net/minecraft/src/BaseMod")
            c("BaseModMp", "net/minecraft/src/BaseModMp")
            c("ModLoader", "net/minecraft/src/ModLoader")
            c("ModLoaderMp", "net/minecraft/src/ModLoaderMp")
            c("mod_BlockHelper", "net/minecraft/src/mod_BlockHelper")
            c("mod_BlockHelper\$Accessor", "net/minecraft/src/mod_BlockHelper\$Accessor")
            c("Packet200ModLoader", "net/minecraft/src/Packet200ModLoader")
            c("Packet230ModLoader", "net/minecraft/src/Packet230ModLoader")
        }
    }

    mods.modImplementation {
        remapper ext.configureSigFixRemapper
    }
}

dependencies {
    clientJarMod "risugami:modloader:${project.mc_version}"
    clientJarMod "modloadermp:modloadermp:${project.mc_version}:client"

    serverJarMod "modloadermp:modloadermp:${project.mc_version}:server"

    mcpcplusImplementation(":craftbukkit-0.0.1-SNAPSHOT_v4")
}
