1 = tile.stone
2 = tile.grass
3 = tile.dirt
4 = tile.stonebrick
5 = tile.wood
6 = tile.sapling
7 = tile.bedrock
8 = tile.water
9 = tile.water
10 = tile.lava
11 = tile.lava
12 = tile.sand
13 = tile.gravel
14 = tile.oreGold
15 = tile.oreIron
16 = tile.oreCoal
17 = tile.log
18 = tile.leaves
19 = tile.sponge
20 = tile.glass
35 = tile.cloth
37 = tile.flower
38 = tile.rose
39 = tile.mushroom
40 = tile.mushroom
41 = tile.blockGold
42 = tile.blockIron
43 = tile.stoneSlab
44 = tile.stoneSlab
45 = tile.brick
46 = tile.tnt
47 = tile.bookshelf
48 = tile.stoneMoss
49 = tile.obsidian
50 = tile.torch
51 = tile.fire
52 = tile.mobSpawner
53 = tile.stairsWood
54 = tile.chest
55 = tile.redstoneDust
56 = tile.oreDiamond
57 = tile.blockDiamond
58 = tile.workbench
59 = tile.crops
60 = tile.farmland
61 = tile.furnace
62 = tile.furnace
63 = tile.sign
64 = tile.doorWood
65 = tile.ladder
66 = tile.rail
67 = tile.stairsStone
68 = tile.sign
69 = tile.lever
70 = tile.pressurePlate
71 = tile.doorIron
72 = tile.pressurePlate
73 = tile.oreRedstone
74 = tile.oreRedstone
75 = tile.notGate
76 = tile.notGate
77 = tile.button
78 = tile.snow
79 = tile.ice
80 = tile.snow
81 = tile.cactus
82 = tile.clay
83 = tile.reeds
84 = tile.jukebox
85 = tile.fence
86 = tile.pumpkin
87 = tile.hellrock
88 = tile.hellsand
89 = tile.lightgem
90 = tile.portal
91 = tile.pumpkin
256 = item.shovelIron
257 = item.pickaxeIron
258 = item.hatchetIron
259 = item.flintAndSteel
260 = item.apple
261 = item.bow
262 = item.arrow
263 = item.coal
264 = item.emerald
265 = item.ingotIron
266 = item.ingotGold
267 = item.swordIron
268 = item.swordWood
269 = item.shovelWood
270 = item.pickaxeWood
271 = item.hatchetWood
272 = item.swordStone
273 = item.shovelStone
274 = item.pickaxeStone
275 = item.hatchetStone
276 = item.swordDiamond
277 = item.shovelDiamond
278 = item.pickaxeDiamond
279 = item.hatchetDiamond
280 = item.stick
281 = item.bowl
282 = item.mushroomStew
283 = item.swordGold
284 = item.shovelGold
285 = item.pickaxeGold
286 = item.hatchetGold
287 = item.string
288 = item.feather
289 = item.sulphur
290 = item.hoeWood
291 = item.hoeStone
292 = item.hoeIron
293 = item.hoeDiamond
294 = item.hoeGold
295 = item.seeds
296 = item.wheat
297 = item.bread
298 = item.helmetCloth
299 = item.chestplateCloth
300 = item.leggingsCloth
301 = item.bootsCloth
302 = item.helmetChain
303 = item.chestplateChain
304 = item.leggingsChain
305 = item.bootsChain
306 = item.helmetIron
307 = item.chestplateIron
308 = item.leggingsIron
309 = item.bootsIron
310 = item.helmetDiamond
311 = item.chestplateDiamond
312 = item.leggingsDiamond
313 = item.bootsDiamond
314 = item.helmetGold
315 = item.chestplateGold
316 = item.leggingsGold
317 = item.bootsGold
318 = item.flint
319 = item.porkchopRaw
320 = item.porkchopCooked
321 = item.painting
322 = item.appleGold
323 = item.sign
324 = item.doorWood
325 = item.bucket
326 = item.bucketWater
327 = item.bucketLava
328 = item.minecart
329 = item.saddle
330 = item.doorIron
331 = item.redstone
332 = item.snowball
333 = item.boat
334 = item.leather
335 = item.milk
336 = item.brick
337 = item.clay
338 = item.reeds
339 = item.paper
340 = item.book
341 = item.slimeball
342 = item.minecartChest
343 = item.minecartFurnace
344 = item.egg
345 = item.compass
346 = item.fishingRod
347 = item.clock
348 = item.yellowDust
349 = item.fishRaw
350 = item.fishCooked
2256 = item.record
2257 = item.record
